---
- name: clone Github webhooks | git
  git:
    repo: "https://github.com/stevenharradine/github-webhooks.git"
    dest: "{{ githubwebhooks_path }}"
    update: yes
    force: yes

- name: copy configuration
  template:
    src: templates/config.js
    dest: "{{ githubwebhooks_path }}/config.js"
    mode: 0644

- name: set cron jobs
  cron:
    name: "cron for {{ item }}"
    user: "{{ githubwebhooks_user }}"
    special_time: daily
    job: "node {{ githubwebhooks_path }}/github-webhooks.js {{ item }}"
  with_items:
    - "--github-repo-filter=ansible-"
    - "--github-repo-filter=playbook-"
