---
- name: clone Github webhooks | git
  git:
    repo: "https://github.com/stevenharradine/github-webhooks.git"
    dest: "/data/www/github-webhooks"
    update: yes
    force: yes

- name: copy configuration
  template:
    src: templates/config.js
    dest: /data/www/github-webhooks/config.js
    mode: 0644
